<a href="https://colab.research.google.com/github/SiangThien/GDDA612_project1/blob/main/GDDA612_Act2_Remove_Duplicates.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
pwd

'/content'

In [ ]:
cd /content/drive/MyDrive

/content/drive/MyDrive

In [ ]:
pwd

'/content/drive/MyDrive'

In [ ]:
ls

 BL-Flickr-Images-Book.csv            Iris.csv                 sample_pandas_normal.csv
'Colab Notebooks'/                    olympics.csv             university_towns.txt
 GDDA612_Wk3_Activity.ipynb           olympics_with_dupl.csv
'How to get started with Drive.pdf'   PandasTutorial/

In [ ]:
dfwd = pd.read_csv('olympics_with_dupl.csv', header=1)
dfwd.head()

,Unnamed: 0,? Summer,01 !,02 !,03 !,Total,? Winter,01 !.1,02 !.1,03 !.1,Total.1,? Games,01 !.2,02 !.2,03 !.2,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12

In [ ]:
new_names =  {'Unnamed: 0': 'Country',
...               '? Summer': 'Summer Olympics',
...               '01 !': 'Gold',
...               '02 !': 'Silver',
...               '03 !': 'Bronze',
...               '? Winter': 'Winter Olympics',
...               '01 !.1': 'Gold.1',
...               '02 !.1': 'Silver.1',
...               '03 !.1': 'Bronze.1',
...               '? Games': '# Games',
...               '01 !.2': 'Gold.2',
...               '02 !.2': 'Silver.2',
...               '03 !.2': 'Bronze.2'}

In [ ]:
dfwd.rename(columns=new_names, inplace=True)

In [ ]:
dfwd

,Country,Summer Olympics,Gold,Silver,Bronze,Total,Winter Olympics,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
145,Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
146,Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
147,Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
148,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [ ]:
dfwd.shape

(149, 16)

In [ ]:
list(dfwd)

['Country',
 'Summer Olympics',
 'Gold',
 'Silver',
 'Bronze',
 'Total',
 'Winter Olympics',
 'Gold.1',
 'Silver.1',
 'Bronze.1',
 'Total.1',
 '# Games',
 'Gold.2',
 'Silver.2',
 'Bronze.2',
 'Combined total']

In [ ]:
dfwd2 = dfwd.set_index('Country')

In [ ]:
# Identify and remove any duplicate records from the dataset

dfwd2.index.duplicated()

array([False, False, False,  True, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [ ]:
print(dfwd2[dfwd2.duplicated()])

                            Summer Olympics  Gold  Silver  Bronze  Total  \
Country
Argentina (ARG)                          23    18      24      28     70
Austria (AUT)                            26    18      33      35     86
Gabon (GAB)                               9     0       1       0      1
Mauritius (MRI)                           8     0       0       1      1
Niger (NIG)                              11     0       0       1      1
United Arab Emirates (UAE)                8     1       0       0      1

                            Winter Olympics  Gold.1  Silver.1  Bronze.1  \
Country
Argentina (ARG)                          18       0         0         0
Austria (AUT)                            22      59        78        81
Gabon (GAB)                               0       0         0         0
Mauritius (MRI)                           0       0         0         0
Niger (NIG)                               0       0         0         0
United Arab Emirates (UAE)                0       0         0         0

                            Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Country
Argentina (ARG)                   0       41      18        24        28
Austria (AUT)                   218       48      77       111       116
Gabon (GAB)                       0        9       0         1         0
Mauritius (MRI)                   0        8       0         0         1
Niger (NIG)                       0       11       0         0         1
United Arab Emirates (UAE)        0        8       1         0         0

                            Combined total
Country
Argentina (ARG)                         70
Austria (AUT)                          304
Gabon (GAB)                              1
Mauritius (MRI)                          1
Niger (NIG)                              1
United Arab Emirates (UAE)               1

In [ ]:
print(dfwd2.duplicated(keep='last'))

Country
Afghanistan (AFG)                               False
Algeria (ALG)                                   False
Argentina (ARG)                                  True
Argentina (ARG)                                 False
Armenia (ARM)                                   False
                                                ...
Independent Olympic Participants (IOP) [IOP]    False
Zambia (ZAM) [ZAM]                              False
Zimbabwe (ZIM) [ZIM]                            False
Mixed team (ZZX) [ZZX]                          False
Totals                                          False
Length: 149, dtype: bool

In [ ]:
print(dfwd2.duplicated().sum())

6

In [ ]:
print(dfwd2.duplicated().value_counts())

False    143
True       6
Name: count, dtype: int64

In [ ]:
print(dfwd2.duplicated(keep=False).value_counts())

False    137
True      12
Name: count, dtype: int64

In [ ]:
print(dfwd2.drop_duplicates())

                                              Summer Olympics  Gold  Silver  \
Country
Afghanistan (AFG)                                          13     0       0
Algeria (ALG)                                              12     5       2
Argentina (ARG)                                            23    18      24
Armenia (ARM)                                               5     1       2
Australasia (ANZ) [ANZ]                                     2     3       4
...                                                       ...   ...     ...
Independent Olympic Participants (IOP) [IOP]                1     0       1
Zambia (ZAM) [ZAM]                                         12     0       1
Zimbabwe (ZIM) [ZIM]                                       12     3       4
Mixed team (ZZX) [ZZX]                                      3     8       5
Totals                                                     27  4809    4775

                                              Bronze  Total  Winter Olympics  \
Country
Afghanistan (AFG)                                  2      2                0
Algeria (ALG)                                      8     15                3
Argentina (ARG)                                   28     70               18
Armenia (ARM)                                      9     12                6
Australasia (ANZ) [ANZ]                            5     12                0
...                                              ...    ...              ...
Independent Olympic Participants (IOP) [IOP]       2      3                0
Zambia (ZAM) [ZAM]                                 1      2                0
Zimbabwe (ZIM) [ZIM]                               1      8                1
Mixed team (ZZX) [ZZX]                             4     17                0
Totals                                          5130  14714               22

                                              Gold.1  Silver.1  Bronze.1  \
Country
Afghanistan (AFG)                                  0         0         0
Algeria (ALG)                                      0         0         0
Argentina (ARG)                                    0         0         0
Armenia (ARM)                                      0         0         0
Australasia (ANZ) [ANZ]                            0         0         0
...                                              ...       ...       ...
Independent Olympic Participants (IOP) [IOP]       0         0         0
Zambia (ZAM) [ZAM]                                 0         0         0
Zimbabwe (ZIM) [ZIM]                               0         0         0
Mixed team (ZZX) [ZZX]                             0         0         0
Totals                                           959       958       948

                                              Total.1  # Games  Gold.2  \
Country
Afghanistan (AFG)                                   0       13       0
Algeria (ALG)                                       0       15       5
Argentina (ARG)                                     0       41      18
Armenia (ARM)                                       0       11       1
Australasia (ANZ) [ANZ]                             0        2       3
...                                               ...      ...     ...
Independent Olympic Participants (IOP) [IOP]        0        1       0
Zambia (ZAM) [ZAM]                                  0       12       0
Zimbabwe (ZIM) [ZIM]                                0       13       3
Mixed team (ZZX) [ZZX]                              0        3       8
Totals                                           2865       49    5768

                                              Silver.2  Bronze.2  \
Country
Afghanistan (AFG)                                    0         2
Algeria (ALG)                                        2         8
Argentina (ARG)                                     24        28
Armenia (ARM)                                        2         9
Australasia (ANZ) [ANZ]                              4         5
...                                                ...       ...
Independent Olympic Participants (IOP) [IOP]         1         2
Zambia (ZAM) [ZAM]                                   1         1
Zimbabwe (ZIM) [ZIM]                                 4         1
Mixed team (ZZX) [ZZX]                               5         4
Totals                                            5733      6078

                                              Combined total
Country
Afghanistan (AFG)                                          2
Algeria (ALG)                                             15
Argentina (ARG)                                           70
Armenia (ARM)                                             12
Australasia (ANZ) [ANZ]                                   12
...                                                      ...
Independent Olympic Participants (IOP) [IOP]               3
Zambia (ZAM) [ZAM]                                         2
Zimbabwe (ZIM) [ZIM]                                       8
Mixed team (ZZX) [ZZX]                                    17
Totals                                                 17579

[143 rows x 15 columns]

In [ ]:
print(dfwd2.drop_duplicates(keep='last'))

                                              Summer Olympics  Gold  Silver  \
Country
Afghanistan (AFG)                                          13     0       0
Algeria (ALG)                                              12     5       2
Argentina (ARG)                                            23    18      24
Armenia (ARM)                                               5     1       2
Australasia (ANZ) [ANZ]                                     2     3       4
...                                                       ...   ...     ...
Independent Olympic Participants (IOP) [IOP]                1     0       1
Zambia (ZAM) [ZAM]                                         12     0       1
Zimbabwe (ZIM) [ZIM]                                       12     3       4
Mixed team (ZZX) [ZZX]                                      3     8       5
Totals                                                     27  4809    4775

                                              Bronze  Total  Winter Olympics  \
Country
Afghanistan (AFG)                                  2      2                0
Algeria (ALG)                                      8     15                3
Argentina (ARG)                                   28     70               18
Armenia (ARM)                                      9     12                6
Australasia (ANZ) [ANZ]                            5     12                0
...                                              ...    ...              ...
Independent Olympic Participants (IOP) [IOP]       2      3                0
Zambia (ZAM) [ZAM]                                 1      2                0
Zimbabwe (ZIM) [ZIM]                               1      8                1
Mixed team (ZZX) [ZZX]                             4     17                0
Totals                                          5130  14714               22

                                              Gold.1  Silver.1  Bronze.1  \
Country
Afghanistan (AFG)                                  0         0         0
Algeria (ALG)                                      0         0         0
Argentina (ARG)                                    0         0         0
Armenia (ARM)                                      0         0         0
Australasia (ANZ) [ANZ]                            0         0         0
...                                              ...       ...       ...
Independent Olympic Participants (IOP) [IOP]       0         0         0
Zambia (ZAM) [ZAM]                                 0         0         0
Zimbabwe (ZIM) [ZIM]                               0         0         0
Mixed team (ZZX) [ZZX]                             0         0         0
Totals                                           959       958       948

                                              Total.1  # Games  Gold.2  \
Country
Afghanistan (AFG)                                   0       13       0
Algeria (ALG)                                       0       15       5
Argentina (ARG)                                     0       41      18
Armenia (ARM)                                       0       11       1
Australasia (ANZ) [ANZ]                             0        2       3
...                                               ...      ...     ...
Independent Olympic Participants (IOP) [IOP]        0        1       0
Zambia (ZAM) [ZAM]                                  0       12       0
Zimbabwe (ZIM) [ZIM]                                0       13       3
Mixed team (ZZX) [ZZX]                              0        3       8
Totals                                           2865       49    5768

                                              Silver.2  Bronze.2  \
Country
Afghanistan (AFG)                                    0         2
Algeria (ALG)                                        2         8
Argentina (ARG)                                     24        28
Armenia (ARM)                                        2         9
Australasia (ANZ) [ANZ]                              4         5
...                                                ...       ...
Independent Olympic Participants (IOP) [IOP]         1         2
Zambia (ZAM) [ZAM]                                   1         1
Zimbabwe (ZIM) [ZIM]                                 4         1
Mixed team (ZZX) [ZZX]                               5         4
Totals                                            5733      6078

                                              Combined total
Country
Afghanistan (AFG)                                          2
Algeria (ALG)                                             15
Argentina (ARG)                                           70
Armenia (ARM)                                             12
Australasia (ANZ) [ANZ]                                   12
...                                                      ...
Independent Olympic Participants (IOP) [IOP]               3
Zambia (ZAM) [ZAM]                                         2
Zimbabwe (ZIM) [ZIM]                                       8
Mixed team (ZZX) [ZZX]                                    17
Totals                                                 17579

[143 rows x 15 columns]

In [ ]:
dfwd

,Country,Summer Olympics,Gold,Silver,Bronze,Total,Winter Olympics,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
145,Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
146,Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
147,Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
148,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [ ]:
dfwd2.drop_duplicates(keep='last', inplace=True)
dfwd2

,Summer Olympics,Gold,Silver,Bronze,Total,Winter Olympics,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Country,,,,,,,,,,,,,,,
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579