<a href="https://colab.research.google.com/github/SiangThien/GDDA612_project1/blob/main/GDDA612_Act2_Standardize_data_types.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
pwd

'/content'

In [ ]:
cd /content/drive/MyDrive

/content/drive/MyDrive

In [ ]:
pwd

'/content/drive/MyDrive'

In [ ]:
ls

 BL-Flickr-Images-Book.csv                   olympics.csv
'Colab Notebooks'/                           olympics_with_dupl.csv
 GDDA612_Act2_Standardize_data_types.ipynb   PandasTutorial/
 GDDA612_Wk3_Activity.ipynb                  sample_pandas_normal.csv
'How to get started with Drive.pdf'          university_towns.txt
 Iris.csv

In [ ]:
dfwd = pd.read_csv('olympics_with_dupl.csv', header=1)
dfwd.head()

,Unnamed: 0,? Summer,01 !,02 !,03 !,Total,? Winter,01 !.1,02 !.1,03 !.1,Total.1,? Games,01 !.2,02 !.2,03 !.2,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12

In [ ]:
new_names =  {'Unnamed: 0': 'Country',
...               '? Summer': 'Summer Olympics',
...               '01 !': 'Gold',
...               '02 !': 'Silver',
...               '03 !': 'Bronze',
...               '? Winter': 'Winter Olympics',
...               '01 !.1': 'Gold.1',
...               '02 !.1': 'Silver.1',
...               '03 !.1': 'Bronze.1',
...               '? Games': '# Games',
...               '01 !.2': 'Gold.2',
...               '02 !.2': 'Silver.2',
...               '03 !.2': 'Bronze.2'}

In [ ]:
dfwd.rename(columns=new_names, inplace=True)

In [ ]:
dfwd

,Country,Summer Olympics,Gold,Silver,Bronze,Total,Winter Olympics,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
145,Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
146,Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
147,Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
148,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [ ]:
dfwd.shape

(149, 16)

In [ ]:
list(dfwd)

['Country',
 'Summer Olympics',
 'Gold',
 'Silver',
 'Bronze',
 'Total',
 'Winter Olympics',
 'Gold.1',
 'Silver.1',
 'Bronze.1',
 'Total.1',
 '# Games',
 'Gold.2',
 'Silver.2',
 'Bronze.2',
 'Combined total']

In [ ]:
# Traverse data frame to detect data types
for column in dfwd.columns:
    print(column,':',pd.api.types.infer_dtype(dfwd[column]))

Country : string
Summer Olympics : integer
Gold : integer
Silver : integer
Bronze : integer
Total : integer
Winter Olympics : integer
Gold.1 : integer
Silver.1 : integer
Bronze.1 : integer
Total.1 : integer
# Games : integer
Gold.2 : integer
Silver.2 : integer
Bronze.2 : integer
Combined total : integer

In [ ]:
# Transforming mixed data types to single data type
dfwd[column] = dfwd[column].apply(lambda x: pd.to_numeric(x, errors = 'ignore'))

In [ ]:
# Traverse data frame to detect data types after fix
for column in dfwd.columns:
    print(column, ':', pd.api.types.infer_dtype(dfwd[column]))

Country : string
Summer Olympics : integer
Gold : integer
Silver : integer
Bronze : integer
Total : integer
Winter Olympics : integer
Gold.1 : integer
Silver.1 : integer
Bronze.1 : integer
Total.1 : integer
# Games : integer
Gold.2 : integer
Silver.2 : integer
Bronze.2 : integer
Combined total : integer